name: Express MongoDB CI/CD

# Memicu workflow saat push ke branch main
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

env:
  MONGODB_URI: mongodb://localhost:27017/test
  NODE_ENV: test
  PORT: 3000

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        mongodb-version: ["5.0"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to production
        run: |
          echo "Deployment step - add your deployment commands here"
          # Contoh deployment ke server:
          # - name: Deploy to VPS
          #   uses: appleboy/ssh-action@master
          #   with:
          #     host: ${{ secrets.HOST }}
          #     username: ${{ secrets.USERNAME }}
          #     key: ${{ secrets.SSH_KEY }}
          #     script: |
          #       cd /var/www/your-app
          #       git pull origin main
          #       npm install
          #       pm2 restart your-app
